version: '3'
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exam_db
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: ruby:3.1
    ports:
      - "7777:7777"
    volumes:
      - ".:/app"
    working_dir: /app
    command: bash -c 'bundle install && ruby db/initialize_db.rb && bundle exec puma -C puma_api.rb'
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exam_db

  web:
    image: ruby:3.1
    ports:
      - "8888:8888"
    volumes:
      - ".:/app"
    working_dir: /app
    command: bash -c 'bundle install && bundle exec puma -C puma_web.rb'
    depends_on:
      - api

  test:
    image: ruby:3.1
    depends_on:
      - api
      - web
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c 'bundle install && bundle exec rspec'
    environment:
      API_URL: "http://api:7777"
      WEB_URL: "http://web:8888"

volumes:
  db-data:
